apiVersion: v1
kind: Namespace
metadata:
  name: example-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: example-nginx-svc
  namespace: example-nginx
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: example-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  namespace: example-nginx
  labels:
    idling.amazee.io/watch: 'true'
  annotations:
    idling.amazee.io/idled: 'true'
    idling.amazee.io/unidle-replicas: '3'
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example-nginx
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: example-nginx
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: example-nginx
  # add annotation to expose the headers to the backend service for 503 only
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
spec:
  rules:
  - host: aergia.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
