controller:
  # config:
  #   custom-http-errors: 404
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  extraArgs:
    default-backend-service: aergia-backend/aergia-backend
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443