name: Aergia Controller Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.21.12, v1.22.9, v1.23.6, v1.24.7]
        experimental: [false]
        include:
          - kindest_node_version: v1.25.0
            experimental: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Set up testing dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential && sudo apt-get clean
    - name: Setup correct Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Install kustomize, kubebuilder, helm
      run: |
        #kubebuilder
        curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz | tar -xz -C /tmp/
        sudo mkdir -p /usr/local/kubebuilder/bin
        sudo mv /tmp/kubebuilder_2.3.2_linux_amd64/bin/* /usr/local/kubebuilder/bin
        chmod +x /usr/local/kubebuilder/bin/*
        echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
    - name: Check go, kustomize, kubebuilder, helm, docker-compose, kind versions
      run: |
        go version
        kustomize version
        helm version
        kubebuilder version
        kind version
    - name: Create kind cluster
      uses: helm/kind-action@v1.3.0
      with:
        version: v0.14.0
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        config: test-resources/kind-cluster.yaml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: amazeeiolocal/aergia:test-tag
    - name: Run Tests
      run: |
        kind load docker-image amazeeiolocal/aergia:test-tag --name chart-testing
        make controller-test